.TH PURA-CLI "1" "June 2016" "pura-cli 0.12"
.SH NAME
pura-cli \- a remote procedure call client for Pura Core. 
.SH SYNOPSIS
pura-cli [options] <command> [params] \- Send command to Pura Core. 
.TP
pura-cli [options] help \- Asks Pura Core for a list of supported commands.
.SH DESCRIPTION
This manual page documents the pura-cli program. pura-cli is an RPC client used to send commands to Pura Core.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

.SH "SEE ALSO"
\fBpurad\fP, \fBpura.conf\fP
.SH AUTHOR
This manual page was written by Ciemon Dunville <ciemon@gmail.com>. Permission is granted to copy, distribute and/or modify this document under the terms of the MIT License.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
